---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu
#    image: quay.io/centos/centos:stream8
#    image: quay.io/centos/ubuntu:latest
    image: pycontribs/ubuntu:latest
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - destroy
    - create
    - converge
    - verify
    - destroy
